name: 01_v2x

channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - ipykernel
  - black
  - pytest
  - ipywidgets
  - numpy
  - bokeh
  - pylint
  - pandas
  - ipympl
  - networkx
  - selenium
  - phantomjs
  - pip
  - pip:
      - git+https://github.com/aladinoster/connectv2x.git@v0.2.0
